jwt:
  secret: ${JWT_SECRET:mySuperSecretKeyThatIsAtLeast32CharsLong12345!}
  expiration: 86400000 # 24 часа

spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/userdb
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: localhost:9092

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 8080