jwt:
  secret: ${JWT_SECRET:mySuperSecretKeyThatIsAtLeast32CharsLong12345!}
  expiration: 86400000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/orderdb
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: localhost:9092

  flyway:
    enabled: true
    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 8081

logging:
  level:
    org.flywaydb: DEBUG